language: r
    
cache: packages

branches:
    only:
        - website-source
        
        
r_packages: 
    - ggplot2
    - dplyr
    - gganimate
    - png
    - gifski
        
r_github_packages:
    - rstudio/blogdown
    
addons:
  apt:
    update: true
    packages:
      - libfreetype6
      - libmagick++-dev
      - cargo
      - libavfilter-dev
    sources:
      - sourceline: 'ppa:cran/ffmpeg-4'
      - sourceline: 'ppa:cran/ffmpeg-3'
      
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

before_script:
    - Rscript -e 'blogdown::install_hugo()'

script:
    - Rscript -e 'blogdown::build_site()'
    
before_deploy:
    - cd $TRAVIS_BUILD_DIR

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: website-source
    local_dir: public
    repo: willdebras/willdebras.github.io
    target_branch: master