baseurl = "https://willdebras.github.io/"
languageCode = "en-US"
title = "Will Bonnell"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "William Bonnell"
  description = "Will Bonnell -- Researcher, programmer, dataviz enthusiast"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Github        = "willdebras"
  Email         = "wtb3na@virginia.edu"
  Twitter       = "_willdebras"
  LinkedIn      = "william-bonnell-85982b3a"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "CV"
  identifier = "cv"
  weight = 300
  url = "/cv"
[[menu.main]]
  name = "dataviz"
  weight = 250
  identifier = "viz"
  url = "/viz/"